version: "3.9"

services:
  db:
    image: postgres:16
    container_name: signalstream_db
    environment:
      POSTGRES_USER: signaluser
      POSTGRES_PASSWORD: signalpass
      POSTGRES_DB: signaldb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
