name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Conan
      - name: Install Conan 2
        run: |
          pip install conan==2.22.2
          conan --version

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Conan install (Release)
        run: |
          conan profile detect --force
          conan install . --build=missing

      - name: Configure CMake
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake \
            -B build

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Run tests (if any)
        run: |
          if [ -d "build/tests" ]; then
            ctest --test-dir build
          else
            echo "No tests directory found â€” skipping."
          fi