name: Build & Compile

on:
  pull_request:
    branches: [ dev, main ]
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------
      # Conan Caching
      # ---------------------------
      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan2/p
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan-${{ runner.os }}-

      - name: Install Conan
        uses: turtlebrowser/get-conan@v2

      - name: Conan profile detect
        run: conan profile detect --force

      - name: Conan install (Release)
        run: |
          conan install . \
            --build=missing \
            -s compiler.cppstd=20

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Configure CMake
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake \
            -B build

      - name: Build
        run: cmake --build build -j

      - name: Run unit tests
        run: echo "No tests yet"