name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------------------------
      # Conan cache
      # ---------------------------
      - name: Cache Conan packages
        uses: actions/cache@v3
        with:
          path: ~/.conan2/p
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan-${{ runner.os }}-

      # ---------------------------
      # Conan
      # ---------------------------
      - name: Install Conan 2
        run: |
          pip install conan==2.22.2
          conan --version

      - name: Detect Conan profile
        run: conan profile detect --force

      # ---------------------------
      # Install dependencies
      # ---------------------------
      - name: Conan install (Release)
        run: |
          conan install . \
            --build=missing \
            -s compiler.cppstd=20

      # ---------------------------
      # Build tools
      # ---------------------------
      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      # ---------------------------
      # Sanity check
      # ---------------------------
      - name: Verify toolchain
        run: |
          test -f build/Release/generators/conan_toolchain.cmake
          echo "Conan toolchain found"

      # ---------------------------
      # Configure
      # ---------------------------
      - name: Configure CMake (tests)
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake \
            -DBUILD_TESTS=ON

      # ---------------------------
      # Build
      # ---------------------------
      - name: Build
        run: cmake --build build -j

      # ---------------------------
      # Run tests
      # ---------------------------
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure